INSERT INTO users(username, password, enabled)
VALUES
	('admin', '{noop}admin', true),
	('user', '{noop}user', true);
	
INSERT INTO authorities(username, authority)
VALUES
	('admin', 'ROLE_USER'),
	('admin', 'ROLE_ADMIN'),
	('user', 'ROLE_USER');

INSERT INTO t_movies(name, release_date, category, description, image, rating)
VALUES
	('The Shawshank Redemption', '1995-03-10', 'Drama', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'https://media.vanityfair.com/photos/541c84101019a3955fea0c49/master/pass/s-vfh-shawshank-redemption-20th-anniversary.jpg', 9.3),
	('The Godfather', '1973-10-01', 'Crime', 'An organized crime dynasty`s aging patriarch transfers control of his clandestine empire to his reluctant son.', 'https://cdn.britannica.com/55/188355-050-D5E49258/Salvatore-Corsitto-The-Godfather-Marlon-Brando-Francis.jpg', 9.2),
	('The Dark Knight', '2008-07-25', 'Action', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.','https://images2.minutemediacdn.com/image/upload/c_crop,h_730,w_1300,x_0,y_10/v1554919442/shape/mentalfloss/dark_knight_hed.png?itok=0a2G7wZC', 9.0),
	('12 Angry Men', '1960-04-01', 'Crime', 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.', 'https://www.privatewriting.com/wp-content/uploads/2021/01/12-Angry-Men-Not-Guilty-Moment.jpg', 9.0),
	('The Lord of the Rings: The Return of the King', '2003-12-13', 'Adventure', 'Gandalf and Aragorn lead the World of Men against Sauron`s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'https://images-na.ssl-images-amazon.com/images/I/81kUINEtUbL._AC_SL1408_.jpg', 8.9),
	('Pulp Fiction', '1995-04-14', 'Crime', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'https://api.time.com/wp-content/uploads/2014/10/pulp-fiction.jpeg', 8.9),
	('Inception', '2010-08-30', 'Action', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'https://omsi.edu/sites/default/files/styles/grid_727x457/public/SFFF16-Inception.jpg?itok=uF8lnE5T', 8.8),
	('The Matrix', '1999-09-03', 'Sci-fi', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 'https://nerdist.com/wp-content/uploads/2019/08/matrix-keanue-reeves-759.jpg', 8.7),
	('Spirited Away', '2001-08-20', 'Animation', 'A 10-year-old girl wanders into a world ruled by witches and spirits, and where humans are changed into beasts.', 'https://static.hollywoodreporter.com/sites/default/files/2020/01/poster02_2_1_1-928x523.jpg', 8.6),
	('The Lion King', '1995-01-20', 'Animation', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.', 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/5249F2C9A2F7F0E1DD33CAE34E26A2794C8F98FAA5DAA9E14E80624A9FCD25A1/scale?width=1200&aspectRatio=1.78&format=jpeg', 8.5);
	

INSERT INTO t_actors(actor_name)
VALUES
	('Morgan Freeman'),
	('Tim Robbins'),
	('Bob Gunton'),
	('William Sadler'),
	('Clancy Brown'),
	('Marlon Brando'),
	('Al Pacino'),
	('James Caan'),
	('Richard S. Castellano'),
	('Robert Duvall'),
	('Christian Bale'),
	('Heath Ledger'),
	('Aaron Eckhart'),
	('Michael Caine'),
	('Maggie Gyllenhaal'),
	('Martin Balsam'),
	('John Fiedler'),
	('Lee J. Cobb'),
	('E.G. Marshall'),
	('Jack Klugman'),
	('Ian McKellen'),
	('Viggo Mortensen'),
	('Sean Astin'),
	('Elijah Wood'),
	('Orlando Bloom'),
	('John Travolta'),
	('Samuel L. Jackson'),
	('Bruce Willis'),
	('Tim Roth'),
	('Amanda Plummer'),
	('Leonardo DiCaprio'),
	('Joseph Gordon-Levitt'),
	('Elliot Page'),
	('Tom Hardy'),
	('Ken Watanabe'),
	('Keanu Reeves'),
	('Laurence Fishburne'),
	('Carrie-Anne Moss'),
	('Hugo Weaving'),
	('Gloria Foster'),
	('Rumi Hiiragi'),
	('Miyu Irino'),
	('Mari Natsuki'),
	('Takashi Naitô'),
	('Yasuko Sawaguchi'),
	('Rowan Atkinson'),
	('Matthew Broderick'),
	('Niketa Calame-Harris'),
	('Jim Cummings'),
	('Whoopi Goldberg');

	

INSERT INTO Movie_Actors(movie_id, actor_id)
VALUES
	(1, 1),
	(1, 2),
	(1, 3),
	(1, 4),
	(1, 5),
	(2, 6),
	(2, 7),
	(2, 8),
	(2, 9),
	(2, 10),
	(3, 11),
	(3, 12),
	(3, 13),
	(3, 14),
	(3, 15),
	(4, 16),
	(4, 17),
	(4, 18),
	(4, 19),
	(4, 20),
	(5, 21),
	(5, 22),
	(5, 23),
	(5, 24),
	(5, 25),
	(6, 26),
	(6, 27),
	(6, 28),
	(6, 29),
	(6, 30),
	(7, 31),
	(7, 32),
	(7, 33),
	(7, 34),
	(7, 35),
	(8, 36),
	(8, 37),
	(8, 38),
	(8, 39),
	(8, 40),
	(9, 41),
	(9, 42),
	(9, 43),
	(9, 44),
	(9, 45),
	(10, 46),
	(10, 47),
	(10, 48),
	(10, 49),
	(10, 50);